name: Update Lambda Clients

on:
  push:
    branches: [main]
    paths:
      - 'lambda_clients/**'
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  update-all-lambdas:
    name: Zip and update ALL Lambda functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js dependencies for Lambdas
        run: |
          find lambda_clients -mindepth 2 -maxdepth 2 -type d | while read dir; do
            if [ -f "$dir/package.json" ]; then
              echo "Installing dependencies in $dir"
              (cd "$dir" && npm install --omit=dev)
            else
              echo "No package.json in $dir, skipping npm install"
            fi
          done

      - name: Zip all lambda functions
        run: |
          find lambda_clients -mindepth 2 -maxdepth 2 -type d | while read dir; do
            name=$(basename "$dir")
            (cd "$dir" && zip -r "../../../lambda_clients/${name}.zip" .)
          done

      - name: Update each Lambda function in AWS
        run: |
          for zip in lambda_clients/*.zip; do
            name=$(basename "$zip" .zip)
            echo "Updating $name from $zip..."
            aws lambda update-function-code \
              --region $AWS_REGION \
              --function-name "$name" \
              --zip-file "fileb://$zip"
          done
