name: Update Lambda Clients

on:
  push:
    branches: [main]
    paths:
      - 'lambda_clients/**'
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  generate-matrix:
    name: Detect changed Lambda functions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for full git history (for origin/main diff)

      - id: set-matrix
        run: |
          chmod +x .github/scripts/generate-matrix-for-lambda-clients.sh
          MATRIX_JSON=$(.github/scripts/generate-matrix-for-lambda-clients.sh)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  update-lambdas:
    name: Zip and update changed Lambdas
    needs: generate-matrix
    runs-on: ubuntu-latest
    if: ${{ needs.generate-matrix.outputs.matrix != '{}' }}
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip code for ${{ matrix.name }}
        run: |
          cd ${{ matrix.path }}
          zip -r ../../${{ matrix.name }}.zip .

      - name: Update Lambda code in AWS
        run: |
          aws lambda update-function-code \
            --region $AWS_REGION \
            --function-name ${{ matrix.name }} \
            --zip-file fileb://lambda_clients/${{ matrix.name }}.zip
